// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: D:/Codes/Lex/test.flex

import java.io.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MyScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900"+
    "\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00\1\u4f00\1\u5000"+
    "\1\u5100\3\u0100\1\u5200\1\u5300\1\u5400\12\u1f00\4\u0100\1\u5500"+
    "\17\u1f00\2\u0100\1\u5600\41\u1f00\2\u0100\1\u5700\1\u5800\2\u1f00"+
    "\1\u5900\1\u5a00\27\u0100\1\u5b00\4\u0100\1\u5c00\1\u5d00\42\u1f00"+
    "\1\u0100\1\u5e00\1\u5f00\11\u1f00\1\u6000\24\u1f00\1\u6100\1\u6200"+
    "\1\u1f00\1\u6300\1\u6400\1\u6500\1\u6600\2\u1f00\1\u6700\5\u1f00"+
    "\1\u6800\1\u6900\1\u6a00\5\u1f00\1\u6b00\1\u6c00\2\u1f00\1\u6d00"+
    "\1\u1f00\1\u6e00\14\u1f00\1\u6f00\4\u1f00\246\u0100\1\u7000\20\u0100"+
    "\1\u7100\1\u7200\25\u0100\1\u7300\34\u0100\1\u7400\14\u1f00\2\u0100"+
    "\1\u7500\5\u1f00\23\u0100\1\u7600\u0aec\u1f00\1\u7700\1\u7800\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\1\1\1\2\1\3\1\4\1\2\1\5\16\0"+
    "\4\6\1\2\1\7\1\10\1\11\1\12\1\7\1\13"+
    "\1\14\2\11\1\15\1\16\1\11\1\17\1\20\1\21"+
    "\1\22\11\23\1\24\1\11\1\25\1\26\1\27\1\24"+
    "\1\6\32\12\1\11\1\30\1\11\1\7\1\12\1\6"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\12\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\12\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\11\1\61\1\11\1\24\6\0\1\62"+
    "\32\0\1\4\1\6\4\12\4\6\1\12\2\6\1\0"+
    "\7\6\1\12\4\6\1\12\5\6\27\12\1\6\37\12"+
    "\1\6\u01ca\12\4\6\14\12\16\6\5\12\7\6\1\12"+
    "\1\6\1\12\21\6\160\0\5\12\1\6\2\12\2\6"+
    "\4\12\1\6\1\12\6\6\1\12\1\6\3\12\1\6"+
    "\1\12\1\6\24\12\1\6\123\12\1\6\213\12\1\6"+
    "\5\0\2\6\246\12\1\6\46\12\2\6\1\12\6\6"+
    "\51\12\6\6\1\12\1\6\55\0\1\6\1\0\1\6"+
    "\2\0\1\6\2\0\1\6\1\0\10\6\33\12\4\6"+
    "\4\12\15\6\6\0\5\6\1\12\4\6\13\0\1\6"+
    "\1\0\3\6\53\12\37\0\4\6\2\12\1\0\143\12"+
    "\1\6\1\12\10\0\1\6\6\0\2\12\2\0\1\6"+
    "\4\0\2\12\12\0\3\12\2\6\1\12\17\6\1\0"+
    "\1\12\1\0\36\12\33\0\2\6\131\12\13\0\1\12"+
    "\16\6\12\0\41\12\11\0\2\12\4\6\1\12\2\6"+
    "\1\0\30\12\4\0\1\12\11\0\1\12\3\0\1\12"+
    "\5\0\22\6\31\12\3\0\4\6\13\12\65\6\25\12"+
    "\1\6\22\12\13\6\61\0\66\12\3\0\1\12\22\0"+
    "\1\12\7\0\12\12\2\0\2\6\12\0\1\6\20\12"+
    "\3\0\1\6\10\12\2\6\2\12\2\6\26\12\1\6"+
    "\7\12\1\6\1\12\3\6\4\12\2\6\1\0\1\12"+
    "\7\0\2\6\2\0\2\6\3\0\1\12\10\6\1\0"+
    "\4\6\2\12\1\6\3\12\2\0\2\6\12\0\4\12"+
    "\7\6\2\12\1\6\1\0\2\6\3\0\1\6\6\12"+
    "\4\6\2\12\2\6\26\12\1\6\7\12\1\6\2\12"+
    "\1\6\2\12\1\6\2\12\2\6\1\0\1\6\5\0"+
    "\4\6\2\0\2\6\3\0\3\6\1\0\7\6\4\12"+
    "\1\6\1\12\7\6\14\0\3\12\1\0\13\6\3\0"+
    "\1\6\11\12\1\6\3\12\1\6\26\12\1\6\7\12"+
    "\1\6\2\12\1\6\5\12\2\6\1\0\1\12\10\0"+
    "\1\6\3\0\1\6\3\0\2\6\1\12\17\6\2\12"+
    "\2\0\2\6\12\0\1\6\1\12\7\6\1\12\6\0"+
    "\1\6\3\0\1\6\10\12\2\6\2\12\2\6\26\12"+
    "\1\6\7\12\1\6\2\12\1\6\5\12\2\6\1\0"+
    "\1\12\7\0\2\6\2\0\2\6\3\0\7\6\3\0"+
    "\4\6\2\12\1\6\3\12\2\0\2\6\12\0\1\6"+
    "\1\12\20\6\1\0\1\12\1\6\6\12\3\6\3\12"+
    "\1\6\4\12\3\6\2\12\1\6\1\12\1\6\2\12"+
    "\3\6\2\12\3\6\3\12\3\6\14\12\4\6\5\0"+
    "\3\6\3\0\1\6\4\0\2\6\1\12\6\6\1\0"+
    "\16\6\12\0\11\6\1\12\6\6\5\0\10\12\1\6"+
    "\3\12\1\6\27\12\1\6\20\12\3\6\1\12\7\0"+
    "\1\6\3\0\1\6\4\0\7\6\2\0\1\6\3\12"+
    "\5\6\2\12\2\0\2\6\12\0\20\6\1\12\3\0"+
    "\1\6\10\12\1\6\3\12\1\6\27\12\1\6\12\12"+
    "\1\6\5\12\2\6\1\0\1\12\7\0\1\6\3\0"+
    "\1\6\4\0\7\6\2\0\7\6\1\12\1\6\2\12"+
    "\2\0\2\6\12\0\1\6\2\12\15\6\4\0\11\12"+
    "\1\6\3\12\1\6\51\12\2\0\1\12\7\0\1\6"+
    "\3\0\1\6\4\0\1\12\5\6\3\12\1\0\7\6"+
    "\3\12\2\0\2\6\12\0\12\6\6\12\1\6\3\0"+
    "\1\6\22\12\3\6\30\12\1\6\11\12\1\6\1\12"+
    "\2\6\7\12\3\6\1\0\4\6\6\0\1\6\1\0"+
    "\1\6\10\0\6\6\12\0\2\6\2\0\15\6\60\12"+
    "\1\0\2\12\7\0\4\6\10\12\10\0\1\6\12\0"+
    "\47\6\2\12\1\6\1\12\1\6\5\12\1\6\30\12"+
    "\1\6\1\12\1\6\12\12\1\0\2\12\11\0\1\12"+
    "\2\6\5\12\1\6\1\12\1\6\6\0\2\6\12\0"+
    "\2\6\4\12\40\6\1\12\27\6\2\0\6\6\12\0"+
    "\13\6\1\0\1\6\1\0\1\6\1\0\4\6\2\0"+
    "\10\12\1\6\44\12\4\6\24\0\1\6\2\0\5\12"+
    "\13\0\1\6\44\0\11\6\1\0\71\6\53\12\24\0"+
    "\1\12\12\0\6\6\6\12\4\0\4\12\3\0\1\12"+
    "\3\0\2\12\7\0\3\12\4\0\15\12\14\0\1\12"+
    "\17\0\2\6\46\12\1\6\1\12\5\6\1\12\2\6"+
    "\53\12\1\6\115\12\1\6\4\12\2\6\7\12\1\6"+
    "\1\12\1\6\4\12\2\6\51\12\1\6\4\12\2\6"+
    "\41\12\1\6\4\12\2\6\7\12\1\6\1\12\1\6"+
    "\4\12\2\6\17\12\1\6\71\12\1\6\4\12\2\6"+
    "\103\12\2\6\3\0\40\6\20\12\20\6\126\12\2\6"+
    "\6\12\3\6\u016c\12\2\6\21\12\1\4\32\12\5\6"+
    "\113\12\3\6\13\12\7\6\15\12\1\6\4\12\3\0"+
    "\13\6\22\12\3\0\13\6\22\12\2\0\14\6\15\12"+
    "\1\6\3\12\1\6\2\0\14\6\64\12\40\0\3\6"+
    "\1\12\3\6\2\12\1\0\2\6\12\0\41\6\4\0"+
    "\1\6\12\0\6\6\131\12\7\6\5\12\2\0\42\12"+
    "\1\0\1\12\5\6\106\12\12\6\37\12\1\6\14\0"+
    "\4\6\14\0\12\6\12\0\36\12\2\6\5\12\13\6"+
    "\54\12\4\6\32\12\6\6\12\0\46\6\27\12\5\0"+
    "\4\6\65\12\12\0\1\6\35\0\2\6\13\0\6\6"+
    "\12\0\15\6\1\12\10\6\16\0\1\6\2\0\77\6"+
    "\5\0\57\12\21\0\7\12\4\6\12\0\21\6\11\0"+
    "\14\6\3\0\36\12\15\0\2\12\12\0\54\12\16\0"+
    "\14\6\44\12\24\0\10\6\12\0\3\6\3\12\12\0"+
    "\44\12\2\6\11\12\7\6\53\12\2\6\3\12\20\6"+
    "\3\0\1\6\25\0\4\12\1\0\6\12\1\0\2\12"+
    "\3\0\1\12\5\6\300\12\72\0\1\6\5\0\26\12"+
    "\2\6\6\12\2\6\46\12\2\6\6\12\2\6\10\12"+
    "\1\6\1\12\1\6\1\12\1\6\1\12\1\6\37\12"+
    "\2\6\65\12\1\6\7\12\1\6\1\12\3\6\3\12"+
    "\1\6\7\12\3\6\4\12\2\6\6\12\4\6\15\12"+
    "\5\6\3\12\1\6\7\12\3\6\13\4\5\0\30\6"+
    "\2\4\5\0\1\4\17\6\2\12\23\6\1\12\12\6"+
    "\1\4\5\0\1\6\12\0\1\6\1\12\15\6\1\12"+
    "\20\6\15\12\3\6\40\12\20\6\15\0\4\6\1\0"+
    "\3\6\14\0\21\6\1\12\4\6\1\12\2\6\12\12"+
    "\1\6\1\12\3\6\5\12\6\6\1\12\1\6\1\12"+
    "\1\6\1\12\1\6\4\12\1\6\13\12\2\6\4\12"+
    "\5\6\5\12\4\6\1\12\21\6\51\12\u0177\6\57\12"+
    "\1\6\57\12\1\6\205\12\6\6\4\12\3\0\2\12"+
    "\14\6\46\12\1\6\1\12\5\6\1\12\2\6\70\12"+
    "\7\6\1\12\17\6\1\0\27\12\11\6\7\12\1\6"+
    "\7\12\1\6\7\12\1\6\7\12\1\6\7\12\1\6"+
    "\7\12\1\6\7\12\1\6\7\12\1\6\40\0\57\6"+
    "\1\12\320\6\1\4\4\6\3\12\31\6\11\12\6\0"+
    "\1\6\5\12\2\6\5\12\4\6\126\12\2\6\2\0"+
    "\2\6\3\12\1\6\132\12\1\6\4\12\5\6\53\12"+
    "\1\6\136\12\21\6\40\12\60\6\320\12\100\6\375\12"+
    "\3\6\215\12\103\6\56\12\2\6\15\12\3\6\20\12"+
    "\12\0\2\12\24\6\57\12\1\0\4\6\12\0\1\6"+
    "\37\12\2\0\120\12\2\0\45\6\11\12\2\6\147\12"+
    "\2\6\65\12\2\6\11\12\52\6\15\12\1\0\3\12"+
    "\1\0\4\12\1\0\27\12\5\0\4\6\1\0\13\6"+
    "\1\12\7\6\64\12\14\6\2\0\62\12\22\0\12\6"+
    "\12\0\6\6\22\0\6\12\3\6\1\12\1\6\2\12"+
    "\13\0\34\12\10\0\2\6\27\12\15\0\14\6\35\12"+
    "\3\6\4\0\57\12\16\0\16\6\1\12\12\0\6\6"+
    "\5\12\1\0\12\12\12\0\5\12\1\6\51\12\16\0"+
    "\11\6\3\12\1\0\10\12\2\0\2\6\12\0\6\6"+
    "\27\12\3\6\1\12\3\0\62\12\1\0\1\12\3\0"+
    "\2\12\2\0\5\12\2\0\1\12\1\0\1\12\30\6"+
    "\3\12\2\6\13\12\5\0\2\6\3\12\2\0\12\6"+
    "\6\12\2\6\6\12\2\6\6\12\11\6\7\12\1\6"+
    "\7\12\1\6\53\12\1\6\16\12\6\6\163\12\10\0"+
    "\1\6\2\0\2\6\12\0\6\6\244\12\14\6\27\12"+
    "\4\6\61\12\4\6\156\12\2\6\152\12\46\6\7\12"+
    "\14\6\5\12\5\6\1\12\1\0\12\12\1\6\15\12"+
    "\1\6\5\12\1\6\1\12\1\6\2\12\1\6\2\12"+
    "\1\6\154\12\41\6\153\12\22\6\100\12\2\6\66\12"+
    "\50\6\15\12\3\6\20\0\20\6\20\0\3\6\2\12"+
    "\30\6\3\12\31\6\1\12\6\6\5\12\1\6\207\12"+
    "\2\6\1\0\4\6\1\12\13\6\12\0\7\6\32\12"+
    "\4\6\1\12\1\6\32\12\13\6\131\12\3\6\6\12"+
    "\2\6\6\12\2\6\6\12\2\6\3\12\3\6\2\12"+
    "\3\6\2\12\22\6\3\0\4\6\14\12\1\6\32\12"+
    "\1\6\23\12\1\6\2\12\1\6\17\12\2\6\16\12"+
    "\42\6\173\12\105\6\65\12\210\6\1\0\202\6\35\12"+
    "\3\6\61\12\17\6\1\0\37\6\40\12\15\6\36\12"+
    "\5\6\46\12\5\0\5\6\36\12\2\6\44\12\4\6"+
    "\10\12\1\6\5\12\52\6\236\12\2\6\12\0\6\6"+
    "\44\12\4\6\44\12\4\6\50\12\10\6\64\12\234\6"+
    "\67\12\11\6\26\12\12\6\10\12\230\6\6\12\2\6"+
    "\1\12\1\6\54\12\1\6\2\12\3\6\1\12\2\6"+
    "\27\12\12\6\27\12\11\6\37\12\101\6\23\12\1\6"+
    "\2\12\12\6\26\12\12\6\32\12\106\6\70\12\6\6"+
    "\2\12\100\6\1\12\3\0\1\6\2\0\5\6\4\0"+
    "\4\12\1\6\3\12\1\6\35\12\2\6\3\0\4\6"+
    "\1\0\40\6\35\12\3\6\35\12\43\6\10\12\1\6"+
    "\34\12\2\0\31\6\66\12\12\6\26\12\12\6\23\12"+
    "\15\6\22\12\156\6\111\12\67\6\63\12\15\6\63\12"+
    "\15\6\44\12\4\0\10\6\12\0\u0146\6\52\12\1\6"+
    "\2\0\3\6\2\12\116\6\35\12\12\6\1\12\10\6"+
    "\26\12\13\0\137\6\25\12\33\6\27\12\11\6\3\0"+
    "\65\12\17\0\37\6\12\0\17\6\4\0\55\12\13\0"+
    "\2\6\1\0\17\6\1\0\2\6\31\12\7\6\12\0"+
    "\6\6\3\0\44\12\16\0\1\6\12\0\4\6\1\12"+
    "\2\0\1\12\10\6\43\12\1\0\2\6\1\12\11\6"+
    "\3\0\60\12\16\0\4\12\4\6\4\0\1\6\14\0"+
    "\1\12\1\6\1\12\43\6\22\12\1\6\31\12\14\0"+
    "\6\6\1\0\101\6\7\12\1\6\1\12\1\6\4\12"+
    "\1\6\17\12\1\6\12\12\7\6\57\12\14\0\5\6"+
    "\12\0\6\6\4\0\1\6\10\12\2\6\2\12\2\6"+
    "\26\12\1\6\7\12\1\6\2\12\1\6\5\12\1\6"+
    "\2\0\1\12\7\0\2\6\2\0\2\6\3\0\2\6"+
    "\1\12\6\6\1\0\5\6\5\12\2\0\2\6\7\0"+
    "\3\6\5\0\213\6\65\12\22\0\4\12\5\6\12\0"+
    "\4\6\1\0\3\12\36\6\60\12\24\0\2\12\1\6"+
    "\1\12\10\6\12\0\246\6\57\12\7\0\2\6\11\0"+
    "\27\6\4\12\2\0\42\6\60\12\21\0\3\6\1\12"+
    "\13\6\12\0\46\6\53\12\15\0\1\12\7\6\12\0"+
    "\66\6\33\12\2\6\17\0\4\6\12\0\306\6\54\12"+
    "\17\0\145\6\100\12\12\0\25\6\10\12\2\6\1\12"+
    "\2\6\10\12\1\6\2\12\1\6\30\12\6\0\1\6"+
    "\2\0\2\6\4\0\1\12\1\0\1\12\2\0\14\6"+
    "\12\0\106\6\10\12\2\6\47\12\7\0\2\6\7\0"+
    "\1\12\1\6\1\12\1\0\33\6\1\12\12\0\50\12"+
    "\7\0\1\12\4\0\10\6\1\0\10\6\1\12\13\0"+
    "\56\12\20\0\3\6\1\12\42\6\71\12\7\6\11\12"+
    "\1\6\45\12\10\0\1\6\10\0\1\12\17\6\12\0"+
    "\30\6\36\12\2\6\26\0\1\6\16\0\111\6\7\12"+
    "\1\6\2\12\1\6\46\12\6\0\3\6\1\0\1\6"+
    "\2\0\1\6\7\0\1\12\1\0\10\6\12\0\6\6"+
    "\6\12\1\6\2\12\1\6\40\12\5\0\1\6\2\0"+
    "\1\6\5\0\1\12\7\6\12\0\u0136\6\23\12\4\0"+
    "\271\6\1\12\54\6\4\12\37\6\232\12\146\6\157\12"+
    "\21\6\304\12\274\6\57\12\1\6\11\0\307\6\107\12"+
    "\271\6\71\12\7\6\37\12\1\6\12\0\146\6\36\12"+
    "\2\6\5\0\13\6\60\12\7\0\11\6\4\12\14\6"+
    "\12\0\11\6\25\12\5\6\23\12\260\6\100\12\200\6"+
    "\113\12\4\6\1\0\1\12\67\0\7\6\4\0\15\12"+
    "\100\6\2\12\1\6\1\12\1\0\13\6\2\0\16\6"+
    "\370\12\10\6\326\12\52\6\11\12\367\6\37\12\61\6"+
    "\3\12\21\6\4\12\10\6\u018c\12\4\6\153\12\5\6"+
    "\15\12\3\6\11\12\7\6\12\12\3\6\2\0\1\6"+
    "\4\0\301\6\5\0\3\6\26\0\2\6\7\0\36\6"+
    "\4\0\224\6\3\0\273\6\125\12\1\6\107\12\1\6"+
    "\2\12\2\6\1\12\2\6\2\12\2\6\4\12\1\6"+
    "\14\12\1\6\1\12\1\6\7\12\1\6\101\12\1\6"+
    "\4\12\2\6\10\12\1\6\7\12\1\6\34\12\1\6"+
    "\4\12\1\6\5\12\1\6\1\12\3\6\7\12\1\6"+
    "\u0154\12\2\6\31\12\1\6\31\12\1\6\37\12\1\6"+
    "\31\12\1\6\37\12\1\6\31\12\1\6\37\12\1\6"+
    "\31\12\1\6\37\12\1\6\31\12\1\6\10\12\2\6"+
    "\151\0\4\6\62\0\10\6\1\0\16\6\1\0\26\6"+
    "\5\0\1\6\17\0\120\6\7\0\1\6\21\0\2\6"+
    "\7\0\1\6\2\0\1\6\5\0\325\6\55\12\3\6"+
    "\7\0\7\12\2\6\12\0\4\6\1\12\u0171\6\54\12"+
    "\16\0\5\6\306\12\13\6\7\0\51\6\104\12\7\0"+
    "\1\12\4\6\12\0\u0156\6\1\12\117\6\4\12\1\6"+
    "\33\12\1\6\2\12\1\6\1\12\2\6\1\12\1\6"+
    "\12\12\1\6\4\12\1\6\1\12\1\6\1\12\6\6"+
    "\1\12\4\6\1\12\1\6\1\12\1\6\1\12\1\6"+
    "\3\12\1\6\2\12\1\6\1\12\2\6\1\12\1\6"+
    "\1\12\1\6\1\12\1\6\1\12\1\6\1\12\1\6"+
    "\2\12\1\6\1\12\2\6\4\12\1\6\7\12\1\6"+
    "\4\12\1\6\4\12\1\6\1\12\1\6\12\12\1\6"+
    "\21\12\5\6\3\12\1\6\5\12\1\6\21\12\u0134\6"+
    "\12\0\6\6\336\12\42\6\65\12\13\6\336\12\2\6"+
    "\u0182\12\16\6\u0131\12\37\6\36\12\342\6\113\12\266\6"+
    "\1\0\36\6\140\0\200\6\360\0\20\6";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[30976];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\2\3\1\4\1\2\1\3\4\2"+
    "\2\5\2\2\17\4\1\2\6\0\1\1\2\0\6\4"+
    "\1\6\4\4\1\6\13\4\2\7\2\10\2\0\1\11"+
    "\32\4\1\0\1\1\33\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\63\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\63\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f"+
    "\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7"+
    "\0\u05fa\0\u062d\0\u0660\0\314\0\u0693\0\u06c6\0\u06f9\0\u072c"+
    "\0\u075f\0\u0231\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990\0\377\0\u09c3\0\u09f6"+
    "\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e"+
    "\0\u0bc1\0\u062d\0\63\0\63\0\u0693\0\u0bf4\0\u0c27\0\u075f"+
    "\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf"+
    "\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57"+
    "\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc\0\u10ef"+
    "\0\u1122\0\u1155\0\u1188\0\u0bf4\0\u11bb\0\u11ee\0\u1221\0\u1254"+
    "\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386\0\u13b9\0\u13ec"+
    "\0\u141f\0\u1452\0\u1485\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u1584"+
    "\0\u15b7\0\u15ea\0\u161d\0\u1650\0\u1683\0\u16b6\0\u16e9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\3\2\1\0\1\3\1\0\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\4\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\14\1\20\1\4\1\21\1\0\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\7\1\31"+
    "\1\7\1\32\4\7\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\3\7\1\41\67\0\1\2\105\0\1\14\34\0"+
    "\2\42\4\43\22\42\1\44\31\42\1\43\2\7\10\0"+
    "\1\7\7\0\2\7\5\0\30\7\1\0\1\7\13\0"+
    "\1\14\12\0\1\14\34\0\14\45\1\0\13\45\1\46"+
    "\32\45\16\0\1\14\7\0\1\14\53\0\1\14\6\0"+
    "\1\14\51\0\1\47\3\0\1\50\4\0\1\14\54\0"+
    "\1\51\1\0\2\52\57\0\1\51\1\0\2\17\64\0"+
    "\1\4\1\14\62\0\1\14\1\4\33\0\2\7\10\0"+
    "\1\7\7\0\2\7\5\0\22\7\1\53\5\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\17\7\1\54"+
    "\10\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\1\55\6\7\1\56\5\7\1\57\12\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\4\7\1\60\10\7"+
    "\1\61\12\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\12\7\1\55\1\7\1\62\10\7\1\63\2\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\12\7"+
    "\1\64\2\7\1\65\12\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\15\7\1\53\12\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\5\7\1\66\6\7"+
    "\1\67\13\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\15\7\1\70\12\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\4\7\1\71\23\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\7\7\1\72\1\73"+
    "\10\7\1\74\2\7\1\75\3\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\26\7\1\76\1\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\14\7\1\77"+
    "\13\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\15\7\1\100\12\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\7\7\1\101\20\7\1\0\1\7\26\0"+
    "\1\14\32\0\1\14\1\0\2\42\4\43\2\42\1\102"+
    "\17\42\1\44\31\42\1\43\10\0\1\103\66\0\1\104"+
    "\46\0\2\45\4\0\6\45\1\105\45\45\1\0\15\106"+
    "\1\107\45\106\3\50\1\2\1\50\1\3\55\50\22\0"+
    "\2\110\37\0\2\7\10\0\1\7\7\0\2\7\5\0"+
    "\21\7\1\111\6\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\4\7\1\112\23\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\20\7\1\113\7\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\1\65\27\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\14\7"+
    "\1\114\13\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\5\7\1\115\22\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\22\7\1\116\5\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\22\7\1\117\5\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\21\7"+
    "\1\120\6\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\15\7\1\121\12\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\17\7\1\66\10\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\12\7\1\122\6\7"+
    "\1\66\6\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\14\7\1\123\13\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\6\7\1\124\11\7\1\125\1\126"+
    "\6\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\15\7\1\127\12\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\6\7\1\130\20\7\1\131\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\1\132\16\7\1\133"+
    "\10\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\10\7\1\134\17\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\16\7\1\135\11\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\10\7\1\136\7\7\1\137"+
    "\7\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\10\7\1\140\1\7\1\141\15\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\10\7\1\142\17\7\1\0"+
    "\1\7\15\106\1\143\62\106\1\143\3\106\1\144\41\106"+
    "\2\7\10\0\1\7\7\0\2\7\5\0\15\7\1\66"+
    "\12\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\1\145\27\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\4\7\1\66\23\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\20\7\1\146\1\147\6\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\1\150\27\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\1\7"+
    "\1\142\26\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\13\7\1\66\14\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\4\7\1\151\23\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\1\146\27\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\10\7\1\152"+
    "\17\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\6\7\1\66\21\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\10\7\1\153\17\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\21\7\1\154\6\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\22\7\1\151"+
    "\5\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\17\7\1\146\10\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\14\7\1\155\13\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\4\7\1\156\23\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\21\7\1\157"+
    "\6\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\22\7\1\160\5\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\21\7\1\161\6\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\4\7\1\162\23\7\1\0"+
    "\3\7\10\0\1\7\7\0\2\7\5\0\15\7\1\163"+
    "\12\7\1\0\3\7\10\0\1\7\7\0\2\7\5\0"+
    "\10\7\1\164\17\7\1\0\3\7\10\0\1\7\7\0"+
    "\2\7\5\0\3\7\1\66\24\7\1\0\3\7\10\0"+
    "\1\7\7\0\2\7\5\0\1\165\27\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\12\7\1\113\15\7"+
    "\1\0\1\7\15\106\1\143\3\106\1\2\41\106\2\7"+
    "\10\0\1\7\7\0\2\7\5\0\11\7\1\66\16\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\21\7"+
    "\1\66\6\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\10\7\1\166\17\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\22\7\1\167\5\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\17\7\1\163\10\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\14\7"+
    "\1\113\13\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\20\7\1\170\7\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\17\7\1\171\10\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\4\7\1\140\23\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\15\7"+
    "\1\172\12\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\10\7\1\173\17\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\2\7\1\146\25\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\2\7\1\174\25\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\3\7"+
    "\1\175\24\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\14\7\1\66\13\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\6\7\1\130\21\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\21\7\1\101\6\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\14\7"+
    "\1\176\13\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\12\7\1\146\15\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\21\7\1\177\6\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\10\7\1\160\17\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\5\7"+
    "\1\66\22\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\2\7\1\66\25\7\1\0\3\7\10\0\1\7"+
    "\7\0\2\7\5\0\7\7\1\66\20\7\1\0\3\7"+
    "\10\0\1\7\7\0\2\7\5\0\4\7\1\172\23\7"+
    "\1\0\3\7\10\0\1\7\7\0\2\7\5\0\22\7"+
    "\1\113\5\7\1\0\3\7\10\0\1\7\7\0\2\7"+
    "\5\0\4\7\1\65\23\7\1\0\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5916];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\5\1\1\11\25\1\6\0"+
    "\1\1\2\0\30\1\2\11\1\1\2\0\33\1\1\0"+
    "\34\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	private int count = 0;

	public void genToken(char[] zzBuffer, int type, int count, int startPos, int endPos) throws IOException{
		FileWriter writer = new FileWriter("out.txt", true);
		String s = String.valueOf(zzBuffer, startPos, endPos - startPos);
		switch(type) {
			// Keyword
			case 0: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<'" + s + "'>," + yyline + ":" + yycolumn +"]\n"); break;
			// Identifier
			case 1: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<Identifier>," + yyline + ":" + yycolumn +"]\n"); break;
			// Operator
			case 2: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<'" + s + "'>," + yyline + ":" + yycolumn +"]\n"); break;
			// Delimiter
			case 3: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<'" + s + "'>," + yyline + ":" + yycolumn +"]\n"); break; 
			// IntegerConstant
			case 4: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<IntegerConstant>," + yyline + ":" + yycolumn +"]\n"); break;
			// FloatConstant
			case 5: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<FloatConstant>," + yyline + ":" + yycolumn +"]\n"); break;
			// CharacterConstant
			case 6: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<CharacterConstant>," + yyline + ":" + yycolumn +"]\n"); break;
			// StringLiteral
			case 7: writer.write("[@" + count + "," + yycolumn + ":" + (yycolumn + endPos - startPos) + "='" + s + "',<StringLiteral>," + yyline + ":" + yycolumn +"]\n"); break;
		}
		writer.flush();
		writer.close();
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MyScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public void scan() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 10: break;
          case 2:
            { count++; genToken(zzBuffer, 2, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 11: break;
          case 3:
            { count++; genToken(zzBuffer, 3, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 12: break;
          case 4:
            { count++; genToken(zzBuffer, 1, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 13: break;
          case 5:
            { count++; genToken(zzBuffer, 4, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 14: break;
          case 6:
            { count++; genToken(zzBuffer, 0, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 15: break;
          case 7:
            { count++; genToken(zzBuffer, 7, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 16: break;
          case 8:
            { count++; genToken(zzBuffer, 6, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 17: break;
          case 9:
            { count++; genToken(zzBuffer, 5, count, zzCurrentPos, zzMarkedPos);
            }
            // fall through
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
